all:
  vars:
    control_plane_endpoint: 192.168.1.100
    load_balancer_ip_pool:
      - 10.0.0.1/24
metal:
  children:
    masters:
      hosts:
        thinkcenter0: {ansible_host: 10.0.0.11, mac: '00:23:24:af:ef:30', disk: sda, network_interface: wlp1s0}
    workers:
      hosts:
        hpz3: {ansible_host: 10.0.0.12, mac: '9c:7b:ef:40:f3:64', disk: sda, network_interface: wlp1s0}
